// SYNOPSIS: #0.main(...)

extern "C" {
    int main(int ac, char **av) {
        Rail<x10aux::ref<String> >* args = x10aux::convert_args(ac, av);
##ifndef NO_EXCEPTIONS
        try {
##endif
        if (x10aux::__here__ == 0) {
            x10aux::general_finish_start();
            #0::main(args);
            x10aux::general_finish_end();
        } else {
            x10aux::general_wait();
        }
##ifndef NO_EXCEPTIONS
        } catch(int exitCode) {
            x10aux::exitCode = exitCode;
        } catch(x10aux::__ref& e) {
            x10aux::ref<Object> &e_ = static_cast<x10aux::ref<Object>&>(e); // TODO: yuck
            fprintf(stderr, "%d: ", (int)x10aux::__here__);
            //fprintf(stderr, "Caught %p\n", ((const x10aux::ref<Exception>&)e)._val);
            fprintf(stderr, "Uncaught exception of type: %s\n", e_->_type()->name().c_str());
            //((const x10aux::ref<Exception>&)e)->printStackTrace();
            x10aux::exitCode = 1;
        } catch(...) {
            fprintf(stderr, "%d: Caught exception\n", (int)x10aux::__here__);
            x10aux::exitCode = 1;
        }
##endif
        x10aux::free_args(args);
        return x10aux::exitCode;
    }
}

// the original app-main method

