// SYNOPSIS: #0.main(...)

extern "C" {
    int main(int ac, char **av) {
        x10::array<x10::ref<String> >* args = x10::convert_args(ac, av);
        try {
		x10::lang::general_finish_start();
		if (__here__ == 0) {
			#0::main(args);
		} else{
			#0::main_np0();
		}
		x10::lang::general_finish_end();
        } catch(int exitCode) {
            x10::exitCode = exitCode;
        } catch(x10::__ref& e) {
            fprintf(stderr, "%d: ", (int)__here__);
            //fprintf(stderr, "Caught %p\n", ((const x10::ref<Exception>&)e)._val);
            ((const x10::ref<Exception>&)e)->printStackTrace(System::x10__out);
            x10::exitCode = 1;
        } catch(...) {
            fprintf(stderr, "%d: Caught exception\n", (int)__here__);
            x10::exitCode = 1;
        }
        x10::free_args(args);
        return x10::exitCode;
    }
}

void #0::main_np0() {
	; 
}
// the original app-main method

